apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    draft: {{ default "draft-app" .Values.draft }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      annotations:
        buildID: {{ .Values.buildID }}
      labels:
        draft: {{ default "draft-app" .Values.draft }}
        app: {{ template "fullname" . }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        command:
          - bundle exec puma -C /usr/src/app/config/puma.rb
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.internalPort }}
        env:
        - name: "ADMIN_EMAILS"
          valueFrom:
            secretKeyRef:
              key:  admin_emails
              name: {{ .Release.Name }}-auth
        - name: "DATABASE_URL"
          valueFrom:
            secretKeyRef:
              key:  database_url
              name: {{ .Release.Name }}-auth
        - name: "SECRET_KEY_BASE"
          valueFrom:
            secretKeyRef:
              key:  secret_key_base
              name: {{ .Release.Name }}-auth
        - name: "SES_PASSWORD"
          valueFrom:
            secretKeyRef:
              key:  ses_password
              name: {{ .Release.Name }}-auth
        - name: "SES_USERNAME"
          valueFrom:
            secretKeyRef:
              key:  ses_username
              name: {{ .Release.Name }}-auth
      {{- range $key, $value := .Values.env }}
        - name: "{{ $key }}"
          value: "{{ $value }}"
      {{- end }}
        resources:
{{ toYaml .Values.resources | indent 12 }}
