apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
data:
  admin_emails: {{ .Values.admin_emails | b64enc | quote  }}
  database_url: {{ .Values.database_url | b64enc | quote  }}
  secret_key_base: {{ .Values.secret_key_base | b64enc | quote  }}
  ses_password: {{ .Values.ses_password | b64enc | quote  }}
  ses_username: {{ .Values.ses_username | b64enc | quote  }}
