
pipeline:
  build:
    image: plugins/docker
    secrets: [ docker_username, docker_password ]
    repo: publicintegrity/klaxon
    tags: latest
    secrets: [ database_url ]
    build_args_from_env: [ DATABASE_URL ]
    when:
      branch: publici

  helm_deploy:
    image: peloton/drone-helm
    chart: ./charts/klaxon
    release: klaxon
    values: image.repository=publicintegrity/klaxon,image.tag=latest,admin_emails=$${ADMIN_EMAILS},database_url=$${DATABASE_URL},secret_key_base=$${SECRET_KEY_BASE},ses_password=$${SES_PASSWORD},ses_username=$${SES_USERNAME}
    prefix:
    namespace: klaxon
    secrets: [ api_server, kubernetes_token, admin_emails, database_url, secret_key_base, ses_password, ses_username ]
    skip_tls_verify: true
    when:
      branch: publici

  slack:
    image: plugins/slack
    secrets: [ slack_webhook ]
    when:
      status: [ success, failure ]
