# Default values for Ruby.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: publicintegrity/klaxon
  tag: latest
  pullPolicy: Always
service:
  name: klaxon
  type: ClusterIP
  externalPort: 80
  internalPort: 3000
resources:
  limits:
    cpu: 100m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi
ingress:
  enabled: true
basedomain: apps.fivetwentyseven.com
env:
  MAILER_FROM_ADDRESS: alerts@publicintegrity.org
  PORT: 3000
  RACK_ENV: production
  RAILS_ENV: production
  SES_ADDRESS: email-smtp.us-east-1.amazonaws.com
  SES_DOMAIN: publicintegrity.org
  SES_PORT: 2587
  SMTP_PROVIDER: SES
nodeSelector:
  cloud.google.com/gke-nodepool: default-pool
